<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="pramit" failures="1" tests="6" name="Test" time="16.953" errors="0" timestamp="2024-02-20T13:56:43 IST">
  <testcase classname="rahulshettyacademyShopping.website.Tests.StandAloneTest" name="failTest" time="0.023">
    <skipped/>
  </testcase> <!-- failTest -->
  <testcase classname="rahulshettyacademyShopping.website.Tests.StandAloneTest" name="failTest" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at rahulshettyacademyShopping.website.Tests.StandAloneTest.failTest(StandAloneTest.java:87)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- failTest -->
  <testcase classname="rahulshettyacademyShopping.website.Tests.StandAloneTest" name="submitOrder" time="9.655"/>
  <testcase classname="rahulshettyacademyShopping.website.Tests.StandAloneTest" name="submitOrder" time="2.091"/>
  <testcase classname="rahulshettyacademyShopping.website.Tests.StandAloneTest" name="orderHistry" time="2.28"/>
  <testcase classname="rahulshettyacademyShopping.website.Tests.StandAloneTest" name="orderHistry" time="2.819"/>
</testsuite> <!-- Test -->
